"""Recreate migrations

Revision ID: e0db236f1a2a
Revises: e019c6625d52
Create Date: 2025-03-19 02:45:42.878882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0db236f1a2a'
down_revision = 'e019c6625d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closet', schema=None) as batch_op:
        batch_op.drop_constraint('closet_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('closet_ibfk_1', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
