"""Recreate migrations

Revision ID: 4652da5698e6
Revises: d5d6fd74caf3
Create Date: 2025-03-19 00:23:52.693755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4652da5698e6'
down_revision = 'd5d6fd74caf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.alter_column('closet_users',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('combination', schema=None) as batch_op:
        batch_op.alter_column('top_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('bottom_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('dress_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('outfit_path',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combination', schema=None) as batch_op:
        batch_op.alter_column('outfit_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=False)
        batch_op.alter_column('dress_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('bottom_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('top_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.alter_column('closet_users',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
