"""Recreate migrations

Revision ID: d473ebf3960e
Revises: a84386ef1853
Create Date: 2025-03-19 03:29:01.508925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd473ebf3960e'
down_revision = 'a84386ef1853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.cid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combination',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('top_id', sa.Integer(), nullable=True),
    sa.Column('bottom_id', sa.Integer(), nullable=True),
    sa.Column('dress_id', sa.Integer(), nullable=True),
    sa.Column('outfit_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['bottom_id'], ['clothing.cid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dress_id'], ['clothing.cid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['top_id'], ['clothing.cid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combination')
    op.drop_table('closet')
    # ### end Alembic commands ###
