"""Recreate migrations

Revision ID: 33774d6158fa
Revises: 
Create Date: 2025-03-18 22:49:54.248889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33774d6158fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combinations')
    op.drop_table('clothing')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('users')
    op.drop_table('closet')
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clothing_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.cid'], name='history_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('closet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clothing_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.cid'], name='closet_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='closet_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.create_table('clothing',
    sa.Column('cid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.ENUM('tops', 'bottoms', 'dresses'), nullable=False),
    sa.Column('caption', mysql.JSON(), nullable=True),
    sa.Column('closet_users', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('cloth_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cloth_mask_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('model_tryon_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('combinations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bottom_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dress_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outfit_path', mysql.VARCHAR(length=225), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['bottom_id'], ['clothing.cid'], name='combinations_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dress_id'], ['clothing.cid'], name='combinations_ibfk_4', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['top_id'], ['clothing.cid'], name='combinations_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='combinations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
