"""Recreate migrations

Revision ID: e019c6625d52
Revises: 4652da5698e6
Create Date: 2025-03-19 00:26:30.608290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e019c6625d52'
down_revision = '4652da5698e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combination', schema=None) as batch_op:
        batch_op.alter_column('outfit_path',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combination', schema=None) as batch_op:
        batch_op.alter_column('outfit_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=False)

    # ### end Alembic commands ###
